export class identifier{
    countries:any;
    functions:any;
    locationnumbers:any;
    locations:any;
    luboil:any;
    origin:any;
    paymentterms:any;
    requisition:any;
    shipclass:any;
    storage:any;
    suppliersubfactors:any;
    supplierscores:any;
    supplierfactors:any;
    typeoffreight:any;
    description:any;
    code:any;
    code1:any;
    code2:any;
}